// lib/laba/petaKategoriShopee.ts — Konversi kategori export Seller Centre (EN "ID - L1/L2/L3")
// ke path kategori_tarif D1 (ID "L1 > L2"). Disusun dari export 2026-10-10 (261 kat) vs 276 path D1.
// Aturan: segmen per segmen via PETA; buang segmen kosong/Others generik; collapse duplikat.
const PETA: Record<string, string> = {
  "home & living": "Perlengkapan Rumah",
  "home appliances": "Elektronik",
  "food & beverages": "Makanan & Minuman",
  "muslim fashion": "Fashion Muslim",
  beauty: "Perawatan & Kecantikan",
  stationery: "Buku & Alat Tulis",
  "mobile & gadgets": "Elektronik",
  health: "Kesehatan",
  "sports & outdoors": "Olahraga & Outdoor",
  automobiles: "Mobil",
  "hobbies & collections": "Hobi & Koleksi",
  "mom & baby": "Ibu & Bayi",
  "women clothes": "Pakaian Wanita",
  "men clothes": "Pakaian Pria",
  "baby & kids fashion": "Fashion Bayi & Anak",
  "women bags": "Tas Wanita",
  "fashion accessories": "Aksesoris Fashion",
  motorcycles: "Sepeda Motor",
  pets: "Hewan Peliharaan",
  audio: "Audio",
  "travel & luggage": "Koper & Tas Travel",
  "computers & accessories": "Komputer & Aksesoris",
  watches: "Jam Tangan",
  "mobile & gadgets": "Elektronik",
  kitchenware: "Perlengkapan Dapur",
  dinnerware: "Peralatan Makan",
  accessories: "Elektronik Lainnya",
  convenience: "Makanan Instan",
  "cooked food": "Makanan Instan",
  "placemats & coasters": "Peralatan Makan",
  "tea pots & sets": "Peralatan Makan",
  pots: "Perlengkapan Dapur",
  "kitchen racks": "Organizer Rumah",
  "grills & accessories": "Perlengkapan Dapur",
  "knives & kitchen scissors": "Perlengkapan Dapur",
  "bakewares & decorations": "Perlengkapan Dapur",
  "measuring glasses & spoons": "Perlengkapan Dapur",
  strainers: "Perlengkapan Dapur",
  "spatulas & cooking tweezers": "Perlengkapan Dapur",
  "graters, peelers & cutters": "Perlengkapan Dapur",
  "kitchen weighing scales": "Perlengkapan Dapur",
  "lighters, matches & fire starters": "Perlengkapan Dapur",
  plates: "Peralatan Makan",
  bowls: "Peralatan Makan",
  "food covers": "Peralatan Makan",
  cutleries: "Peralatan Makan",
  "jugs, pitchers & accessories": "Peralatan Makan",
  "cups, mugs & glasses": "Peralatan Makan",
  "water bottles & accessories": "Peralatan Makan",
  straws: "Peralatan Makan",
  "disposable tableware": "Peralatan Makan",
  furniture: "Furniture",
  wardrobes: "Furniture",
  "cupboards & cabinets": "Furniture",
  "shelves & racks": "Furniture",
  "desks & tables": "Furniture",
  "benches, chairs & stools": "Furniture",
  "home organizers": "Organizer Rumah",
  "storage boxes, bags & baskets": "Organizer Rumah",
  "desk organizers": "Organizer Rumah",
  "hangers & pegs": "Organizer Rumah",
  "laundry bags & baskets": "Organizer Rumah",
  "shoe storage boxes": "Organizer Rumah",
  "home care supplies": "Perawatan Rumah",
  "basins, buckets & water dippers": "Perawatan Rumah",
  "clotheslines & drying racks": "Perawatan Rumah",
  "tissue & paper towels": "Perawatan Rumah",
  "trash & recycling bins": "Perawatan Rumah",
  "cleaning agents": "Perawatan Rumah",
  brooms: "Perawatan Rumah",
  mops: "Perawatan Rumah",
  "cleaning cloths": "Perawatan Rumah",
  "laundry care": "Perawatan Rumah",
  "fabric fragrances": "Perawatan Rumah",
  detergents: "Perawatan Rumah",
  decoration: "Dekorasi",
  "floor mats": "Dekorasi",
  "carpets & rugs": "Dekorasi",
  "curtains & blinds": "Dekorasi",
  "photo frames & wall decoration": "Dekorasi",
  "table cloths": "Dekorasi",
  bedding: "Kamar Tidur",
  pillows: "Kamar Tidur",
  bathrooms: "Kamar Mandi",
  "towels & bathrobes": "Kamar Mandi",
  "bath towels": "Kamar Mandi",
  "bathroom racks & cabinets": "Kamar Mandi",
  gardening: "Taman",
  fertilizer: "Taman",
  "pots & planters": "Taman",
  "party supplies": "Perlengkapan Pesta",
  lighting: "Lampu",
  "tools & home improvement": "Alat Pertukangan & Renovasi Rumah",
  tools: "Alat Pertukangan & Renovasi Rumah",
  "water pumps, parts & accessories": "Alat Pertukangan & Renovasi Rumah",
  "industrial adhesives & tapes": "Alat Pertukangan & Renovasi Rumah",
  "kitchen appliances": "Perangkat Dapur",
  "stoves, hobs & gas regulators": "Perangkat Dapur",
  "large household appliances": "Peralatan Listrik Besar",
  cooling: "Peralatan Listrik Besar",
  fans: "Peralatan Listrik Besar",
  "small household appliances": "Peralatan Listrik Kecil",
  "irons & steamers": "Peralatan Listrik Kecil",
  "juicers, blenders & soya bean machines": "Perangkat Dapur",
  "water filters, coolers & dispensers": "Perangkat Dapur",
  mixers: "Perangkat Dapur",
  "rice cookers": "Perangkat Dapur",
  refrigerators: "Peralatan Listrik Besar",
  snacks: "Makanan Ringan",
  "chips & crisps": "Makanan Ringan",
  "biscuits, cookies & wafers": "Roti & Kue",
  "pudding, jellies & marshmallow": "Makanan Ringan",
  "gift set & hampers": "Set Hadiah & Hampers",
  "convenience / ready-to-eat": "Makanan Instan",
  "instant noodles": "Makanan Instan",
  beverages: "Minuman",
  "cordial & syrups": "Minuman",
  "kid muslim wear": "Pakaian Muslim Anak",
  "girl's muslim attire": "Pakaian Muslim Anak",
  veils: "Pakaian Muslim Wanita",
  "men muslim wear": "Pakaian Muslim Pria",
  sarong: "Pakaian Muslim Pria",
  "women muslim wear": "Pakaian Muslim Wanita",
  pashmina: "Pakaian Muslim Wanita",
  "prayer attire & equipment": "Mukena & Perlengkapan Sholat",
  "peci, songkok & kopiah": "Mukena & Perlengkapan Sholat",
  "pants & leggings": "Celana Panjang & Legging",
  "leggings & treggings": "Celana Panjang & Legging",
  "innerwear & underwear": "Pakaian Dalam",
  underwear: "Pakaian Dalam",
  "crossbody & shoulder bags": "Tas Selempang & Bahu Wanita",
  "additional accessories": "Aksesoris Tambahan",
  masks: "Aksesoris Tambahan",
  gloves: "Sarung Tangan",
  "baby & kids accessories": "Aksesoris Bayi & Anak",
  socks: "Pakaian Anak Laki-Laki",
  "perfumes & fragrances": "Parfum & Wewangian",
  "hand, foot & nail care": "Perawatan Tangan, Kaki & Kuku",
  "hand care": "Perawatan Tangan, Kaki & Kuku",
  "hand washes": "Perawatan Tangan, Kaki & Kuku",
  "men's care": "Perawatan Pria",
  "shaving & grooming": "Perawatan Pria",
  shavers: "Perawatan Pria",
  "beauty tools": "Alat Kecantikan",
  "hair tools": "Alat Kecantikan",
  "hair styling appliances": "Alat Kecantikan",
  "makeup accessories": "Alat Kecantikan",
  "body deodorants": "Perawatan Tubuh",
  "medical supplies": "Obat-obatan & Alat Kesehatan",
  "medical gloves & masks": "Obat-obatan & Alat Kesehatan",
  "scale & body fat analyzers": "Obat-obatan & Alat Kesehatan",
  "sports & outdoor accessories": "Aksesoris Olahraga & Aktivitas Outdoor",
  "rain coats": "Pakaian Olahraga & Aktivitas Outdoor",
  umbrellas: "Aksesoris Olahraga & Aktivitas Outdoor",
  "automobile interior accessories": "Aksesoris Interior Mobil",
  "perfumes, air fresheners & purifiers": "Aksesoris Interior Mobil",
  "car mattresses": "Aksesoris Interior Mobil",
  souvenirs: "Souvenir & Hadiah",
  "coin banks": "Souvenir & Hadiah",
  "school & office equipment": "Perlengkapan Sekolah & Kantor",
  "strings & tapes": "Perlengkapan Sekolah & Kantor",
  "cables, chargers & converters": "Elektronik Lainnya",
  "mobile cables & converters": "Elektronik Lainnya",
  chargers: "Elektronik Lainnya",
  "travel adaptors": "Elektronik Lainnya",
  "powerbanks & batteries": "Elektronik Lainnya",
  powerbanks: "Elektronik Lainnya",
  "selfie accessories": "Elektronik Lainnya",
  "selfie sticks": "Elektronik Lainnya",
  "motorcycle accessories": "Aksesoris Sepeda Motor",
  "seats & seat covers": "Aksesoris Sepeda Motor",
  "motorcycle spare parts": "Suku Cadang Motor",
  "exhaust & emissions": "Suku Cadang Motor",
  "motorcycle helmets & accessories": "Helm & Aksesoris Pengendara Motor",
  "food supplement": "Suplemen Makanan",
  "well being": "Suplemen Makanan",
  "sports & outdoor recreation equipments": "Alat Rekreasi Olahraga & Aktivitas Outdoor",
  "sports & outdoor apparels": "Pakaian Olahraga & Aktivitas Outdoor",
  bottoms: "Pakaian Olahraga & Aktivitas Outdoor",
  "electrical circuitry & parts": "Kelistrikan",
  "electric sockets & extension cords": "Kelistrikan",
  "fresh & frozen food": "Makanan Segar & Beku",
  meat: "Makanan Segar & Beku",
  poultry: "Makanan Segar & Beku",
  "cooking essentials": "Kebutuhan Memasak",
  "food staples": "Bahan Pokok",
  "canned food": "Bahan Pokok",
  "canned seafood": "Bahan Pokok",
  "lingerie & underwear": "Pakaian Dalam",
  "personal care": "Perawatan Diri",
  "girl clothes": "Pakaian Anak Perempuan",
  tops: "Pakaian Anak Perempuan",
  "t-shirts": "Pakaian Anak Perempuan",
  "boy clothes": "Pakaian Anak Laki-Laki",
  shorts: "Celana Pendek",
  pants: "Celana Panjang",
  jeans: "Celana Panjang Jeans",
  joggers: "Celana Panjang",
  cargo: "Celana Panjang",
  "tote bags": "Tote Bag",
  "top-handle bags": "Top Handle Bag",
  "toys & games": "Mainan & Games",
  toys: "Mainan",
  "toy vehicles": "Mainan",
  "tvs & accessories": "TV & Aksesoris",
  "sleepwear & pajamas": "Pakaian Tidur & Piyama",
  dresses: "Dress",
  "breakfast cereals & spread": "Menu Sarapan",
  "pet accessories": "Aksesoris Hewan Peliharaan",
  "pet food": "Makanan Hewan",
  "cat food": "Makanan Hewan",
  "beauty sets & packages": "Paket & Set Kecantikan",
  skincare: "Perawatan Wajah",
  "notebooks & papers": "Buku Tulis & Kertas",
  "thermal paper & continuous paper": "Buku Tulis & Kertas",
  "home audio & speakers": "Perangkat Audio & Speaker",
  speakers: "Perangkat Audio & Speaker",
  "feeding essentials": "Perlengkapan Makan Bayi",
  utensils: "Perlengkapan Makan Bayi",
  "baby food containers": "Perlengkapan Makan Bayi",
  "highchairs & booster seats": "Kamar Bayi",
  "writing & correction": "Alat Tulis",
  "eraser & correction supplies": "Alat Tulis",
  bakery: "Roti & Kue",
  "cakes & pies": "Roti & Kue",
  "diapering & potty": "Popok & Pispot",
  "disposable diapers": "Popok & Pispot",
  "gift & wrapping": "Pembungkus Kado & Kemasan",
  "bubble wraps": "Pembungkus Kado & Kemasan",
  "bath & body care": "Perawatan Tubuh",
  "bathing tubs & seats": "Perlengkapan Mandi",
  "baby travel essentials": "Perlengkapan Travelling Bayi",
  "peripherals & accessories": "Aksesoris Desktop & Laptop",
  "women watches": "Jam Tangan Wanita",
  "travel accessories": "Aksesoris Travel",
  "travel bags": "Tas Travel",
  "accessories sets & packages": "Set & Paket Aksesoris",
  "automotive care": "Perawatan Kendaraan",
  others: "",
  "perlengkapan rumah lainnya": "",
  lainnya: "",
  "cooked food": "Makanan Instan",
  "bathing tubs & seats": "Perlengkapan Mandi",
};

/** Koreksi full-path pasca-segmen (kasus "Others" generik). */
const PETA_FULL: Record<string, string> = {
  "kesehatan > lainnya": "Kesehatan > Kesehatan Lainnya",
  "perlengkapan rumah > lainnya": "Perlengkapan Rumah > Perlengkapan Rumah Lainnya",
  "elektronik > lainnya": "Elektronik > Elektronik Lainnya",
  "pakaian pria > lainnya": "Pakaian Pria > Pakaian Pria Lainnya",
  "ibu & bayi > perawatan tubuh": "Ibu & Bayi > Ibu & Bayi Lainnya",
  "ibu & bayi > perawatan tubuh > perlengkapan mandi": "Ibu & Bayi > Perlengkapan Mandi",
  kesehatan: "Kesehatan > Kesehatan Lainnya",
  "perlengkapan rumah": "Perlengkapan Rumah > Perlengkapan Rumah Lainnya",
  elektronik: "Elektronik > Elektronik Lainnya",
  "pakaian pria": "Pakaian Pria > Pakaian Pria Lainnya",
};

const PETA_NORM: Record<string, string> = Object.fromEntries(
  Object.entries(PETA).map(([k, v]) => [k.toLowerCase(), v])
);

/** Konversi satu kategori export EN → path ID. Null bila tak terpetakan sama sekali. */
export function kategoriExportKeID(katEn: string): string | null {
  const segs = katEn
    .replace(/^\d+\s*-\s*/, "")
    .split("/")
    .map((s) => (PETA_NORM[s.toLowerCase().trim()] ?? s).trim())
    .filter(Boolean)
    .filter((s, i, a) => i === 0 || s.toLowerCase() !== a[i - 1].toLowerCase());
  if (segs.length === 0) return null;
  const gabung = segs.join(" > ");
  return PETA_FULL[gabung.toLowerCase()] ?? gabung;
}
